### ISSUE TITLE
Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.

### ISSUE THREAD

**Issue by svcarlsen** [vinaygoel/ars-workshop#4]
I get this error when running Exercise 6  and  on RHEL 6.6:
(And similar for Excercise 4)

[hadoop@dia-prod-udv-01 ars-workshop]$ pig -x local -p I_WAT_DIR=$ARS_EXERCISES_DERIVATIVES_DIR/sample-wat/*.wat.gz -p O_DATE_LAT_LONG_COUNT_DIR=$ARS_EXERCISES_RESULTS_DIR/date-lat-long-count/ pig/geoip-from-wat.pig
2015-08-14 16:02:39,600 [main] INFO  org.apache.pig.Main - Apache Pig version 0.12.0-cdh5.0.1 (rexported) compiled May 06 2014, 13:43:04
2015-08-14 16:02:39,601 [main] INFO  org.apache.pig.Main - Logging error messages to: /home/hadoop/ars-workshop/pig_1439560959585.log
2015-08-14 16:02:39,848 [main] WARN  org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-08-14 16:02:40,090 [main] INFO  org.apache.pig.impl.util.Utils - Default bootup file /home/hadoop/.pigbootup not found
2015-08-14 16:02:40,226 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-08-14 16:02:40,227 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2015-08-14 16:02:40,232 [main] INFO  org.apache.pig.backend.hadoop.executionengine.HExecutionEngine - Connecting to hadoop file system at: file:///
2015-08-14 16:02:40,279 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.cache.files is deprecated. Instead, use mapreduce.job.cache.files
2015-08-14 16:02:40,288 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.max.map.failures.percent is deprecated. Instead, use mapreduce.map.failures.maxpercent
2015-08-14 16:02:40,344 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - fs.default.name is deprecated. Instead, use fs.defaultFS
2015-08-14 16:02:40,358 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - created tmp python.cachedir=/tmp/pig_jython_4270165852941165128
2015-08-14 16:02:43,309 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.parse_entity_map
2015-08-14 16:02:43,731 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.get_entity_bags
2015-08-14 16:02:43,733 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.getHostFromSurtUrl
2015-08-14 16:02:43,734 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.getDateFormatFromWARCTS
2015-08-14 16:02:43,735 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.collectBagElements
2015-08-14 16:02:43,735 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.remove_chars
2015-08-14 16:02:43,740 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.getTLDFromDomain
2015-08-14 16:02:43,747 [main] INFO  org.apache.pig.scripting.jython.JythonScriptEngine - Register scripting UDF: derivativeUtils.getClassicTSFormatFromWARCTS
2015-08-14 16:02:44,116 [main] INFO  org.apache.pig.scripting.jython.JythonFunction - Schema 'text:chararray' defined for func getDateFormatFromWARCTS
2015-08-14 16:02:44,250 [main] INFO  org.apache.pig.tools.pigstats.ScriptState - Pig features used in the script: GROUP_BY,STREAMING,FILTER
2015-08-14 16:02:44,282 [main] INFO  org.apache.pig.newplan.logical.optimizer.LogicalPlanOptimizer - {RULES_ENABLED=[AddForEach, ColumnMapKeyPrune, DuplicateForEachColumnRewrite, GroupByConstParallelSetter, ImplicitSplitInserter, LimitOptimizer, LoadTypeCastInserter, MergeFilter, MergeForEach, NewPartitionFilterOptimizer, PartitionFilterOptimizer, PushDownForEachFlatten, PushUpFilter, SplitFilter, StreamTypeCastInserter], RULES_DISABLED=[FilterLogicExpressionSimplifier]}
2015-08-14 16:02:44,311 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.textoutputformat.separator is deprecated. Instead, use mapreduce.output.textoutputformat.separator
2015-08-14 16:02:44,457 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MRCompiler - File concatenation threshold: 100 optimistic? false
2015-08-14 16:02:44,478 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.CombinerOptimizer - Choosing to move algebraic foreach to combiner
2015-08-14 16:02:44,485 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.CombinerOptimizer - Choosing to move algebraic foreach to combiner
2015-08-14 16:02:44,502 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MultiQueryOptimizer - MR plan size before optimization: 2
2015-08-14 16:02:44,502 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MultiQueryOptimizer - MR plan size after optimization: 2
2015-08-14 16:02:44,525 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Initializing JVM Metrics with processName=JobTracker, sessionId=
2015-08-14 16:02:44,543 [main] INFO  org.apache.pig.tools.pigstats.ScriptState - Pig script settings are added to the job
2015-08-14 16:02:44,655 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.reduce.markreset.buffer.percent is deprecated. Instead, use mapreduce.reduce.markreset.buffer.percent
2015-08-14 16:02:44,655 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - mapred.job.reduce.markreset.buffer.percent is not set, set to default 0.3
2015-08-14 16:02:44,655 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.output.compress is deprecated. Instead, use mapreduce.output.fileoutputformat.compress
2015-08-14 16:02:44,657 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - Reduce phase detected, estimating # of required reducers.
2015-08-14 16:02:44,658 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - Using reducer estimator: org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.InputSizeReducerEstimator
2015-08-14 16:02:44,665 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.InputSizeReducerEstimator - BytesPerReducer=1000000000 maxReducers=999 totalInputFileSize=420051317
2015-08-14 16:02:44,665 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - Setting Parallelism to 1
2015-08-14 16:02:44,665 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.reduce.tasks is deprecated. Instead, use mapreduce.job.reduces
2015-08-14 16:02:44,710 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.JobControlCompiler - Setting up single store job
2015-08-14 16:02:44,717 [main] INFO  org.apache.pig.data.SchemaTupleFrontend - Key [pig.schematuple] is false, will not generate code.
2015-08-14 16:02:44,717 [main] INFO  org.apache.pig.data.SchemaTupleFrontend - Starting process to move generated code to distributed cache
2015-08-14 16:02:44,717 [main] INFO  org.apache.pig.data.SchemaTupleFrontend - Distributed cache not supported or needed in local mode. Setting key [pig.schematuple.local.dir] with code temp directory: /tmp/1439560964717-0
2015-08-14 16:02:44,820 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 1 map-reduce job(s) waiting for submission.
2015-08-14 16:02:44,821 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker.http.address is deprecated. Instead, use mapreduce.jobtracker.http.address
2015-08-14 16:02:44,841 [JobControl] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2015-08-14 16:02:45,008 [JobControl] WARN  org.apache.hadoop.mapreduce.JobSubmitter - No job jar file set.  User classes may not be found. See Job or Job#setJar(String).
2015-08-14 16:02:45,083 [JobControl] INFO  org.apache.hadoop.mapreduce.lib.input.FileInputFormat - Total input paths to process : 3
2015-08-14 16:02:45,144 [JobControl] INFO  org.apache.hadoop.mapreduce.JobSubmitter - number of splits:3
2015-08-14 16:02:45,464 [JobControl] INFO  org.apache.hadoop.mapreduce.JobSubmitter - Submitting tokens for job: job_local1780770555_0001
2015-08-14 16:02:45,790 [JobControl] WARN  org.apache.hadoop.conf.Configuration - file:/tmp/hadoop-hadoop/mapred/staging/hadoop1780770555/.staging/job_local1780770555_0001/job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2015-08-14 16:02:45,791 [JobControl] WARN  org.apache.hadoop.conf.Configuration - file:/tmp/hadoop-hadoop/mapred/staging/hadoop1780770555/.staging/job_local1780770555_0001/job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2015-08-14 16:02:46,289 [LocalDistributedCacheManager Downloader #0] WARN  org.apache.hadoop.security.UserGroupInformation - PriviledgedActionException as:hadoop (auth:SIMPLE) cause:java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
2015-08-14 16:02:46,290 [JobControl] INFO  org.apache.hadoop.mapreduce.JobSubmitter - Cleaning up the staging area file:/tmp/hadoop-hadoop/mapred/staging/hadoop1780770555/.staging/job_local1780770555_0001
2015-08-14 16:02:46,290 [JobControl] WARN  org.apache.hadoop.security.UserGroupInformation - PriviledgedActionException as:hadoop (auth:SIMPLE) cause:java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
2015-08-14 16:02:46,291 [JobControl] INFO  org.apache.hadoop.mapreduce.lib.jobcontrol.ControlledJob - PigLatin:geoip-from-wat.pig got an error while submitting 
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
    at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:149)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.<init>(LocalJobRunner.java:163)
    at org.apache.hadoop.mapred.LocalJobRunner.submitJob(LocalJobRunner.java:731)
    at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1295)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1292)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:1292)
    at org.apache.hadoop.mapreduce.lib.jobcontrol.ControlledJob.submit(ControlledJob.java:335)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.pig.backend.hadoop23.PigJobControl.submit(PigJobControl.java:128)
    at org.apache.pig.backend.hadoop23.PigJobControl.run(PigJobControl.java:191)
    at java.lang.Thread.run(Thread.java:724)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher$1.run(MapReduceLauncher.java:270)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:145)
    ... 18 more
Caused by: java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
    at org.apache.hadoop.yarn.util.FSDownload.copy(FSDownload.java:245)
    at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:58)
    at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:343)
    at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:341)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
    at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:340)
    at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:57)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
2015-08-14 16:02:46,301 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - HadoopJobId: job_local1780770555_0001
2015-08-14 16:02:46,302 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Processing aliases IP,IPGrp,Lines,Result
2015-08-14 16:02:46,302 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - detailed locations: M: IP[22,5],IP[-1,-1],null[-1,-1],IP[27,5],IP[28,5],Result[30,9],IPGrp[29,8] C: Result[30,9],IPGrp[29,8] R: Result[30,9],Lines[32,8],Lines[-1,-1]
2015-08-14 16:02:46,304 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 0% complete
2015-08-14 16:02:46,406 [LocalDistributedCacheManager Downloader #2] WARN  org.apache.hadoop.security.UserGroupInformation - PriviledgedActionException as:hadoop (auth:SIMPLE) cause:java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/GeoLiteCity.dat is not publicly accessable and as such cannot be part of the public cache.
2015-08-14 16:02:46,808 [main] WARN  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Ooops! Some job has failed! Specify -stop_on_failure if you want Pig to stop immediately on failure.
2015-08-14 16:02:46,808 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - job job_local1780770555_0001 has failed! Stop running all dependent jobs
2015-08-14 16:02:46,808 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 100% complete
2015-08-14 16:02:46,809 [main] ERROR org.apache.pig.tools.pigstats.PigStatsUtil - 1 map reduce job(s) failed!
2015-08-14 16:02:46,809 [main] INFO  org.apache.pig.tools.pigstats.SimplePigStats - Detected Local mode. Stats reported below may be incomplete
2015-08-14 16:02:46,812 [main] INFO  org.apache.pig.tools.pigstats.SimplePigStats - Script Statistics: 

HadoopVersion   PigVersion  UserId  StartedAt   FinishedAt  Features
2.3.0-cdh5.0.1  0.12.0-cdh5.0.1 hadoop  2015-08-14 16:02:44 2015-08-14 16:02:46 GROUP_BY,STREAMING,FILTER

Failed!

Failed Jobs:
JobId   Alias   Feature Message Outputs
job_local1780770555_0001    IP,IPGrp,Lines,Result   GROUP_BY,STREAMING,COMBINER Message: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
    at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:149)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.<init>(LocalJobRunner.java:163)
    at org.apache.hadoop.mapred.LocalJobRunner.submitJob(LocalJobRunner.java:731)
    at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1295)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1292)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:1292)
    at org.apache.hadoop.mapreduce.lib.jobcontrol.ControlledJob.submit(ControlledJob.java:335)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.pig.backend.hadoop23.PigJobControl.submit(PigJobControl.java:128)
    at org.apache.pig.backend.hadoop23.PigJobControl.run(PigJobControl.java:191)
    at java.lang.Thread.run(Thread.java:724)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher$1.run(MapReduceLauncher.java:270)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:145)
    ... 18 more
Caused by: java.io.IOException: Resource file:/home/hadoop/ars-workshop/cache/geo-pack.tgz is not publicly accessable and as such cannot be part of the public cache.
    at org.apache.hadoop.yarn.util.FSDownload.copy(FSDownload.java:245)
    at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:58)
    at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:343)
    at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:341)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
    at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:340)
    at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:57)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

Input(s):
Failed to read data from "/home/hadoop/ars-workshop/data/ars-exercises-derivatives/sample-wat/*.wat.gz"

Output(s):

Job DAG:
job_local1780770555_0001    ->  null,
null

2015-08-14 16:02:46,812 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Failed!
2015-08-14 16:02:46,813 [main] ERROR org.apache.pig.tools.grunt.GruntParser - ERROR 2244: Job failed, hadoop does not return any error message
Details at logfile: /home/hadoop/ars-workshop/pig_1439560959585.log
2015-08-14 16:02:46,814 [main] ERROR org.apache.pig.tools.grunt.GruntParser - ERROR 2244: Job failed, hadoop does not return any error message
Details at logfile: /home/hadoop/ars-workshop/pig_1439560959585.log

**Comment by vinaygoel** [comment]
See related: https://issues.apache.org/jira/browse/HADOOP-10191

A workaround would be to checkout / copy the workshop into your /tmp/ folder instead of /home/

**Comment by svcarlsen** [comment]
Thanks for the workaround.

**Comment by hhland** [comment]
very greate
